name: 'Swift Android Action'
description: 'Cross-compiles a swift package for Android and runs the test cases in an Android emulator'
branding:
  icon: 'target'
  color: 'orange'
outputs:
  swift-build:
    description: 'The swift build command using the installed toolchain and SDK'
    value: ${{ steps.install.outputs.swiftcmd }}
  swift-sdk:
    description: 'The swift SDK that is used to build for Android'
    value: ${{ steps.install.outputs.swift-sdk }}
inputs:
  swift-version:
    description: 'The version of the Swift toolchain to use'
    required: true
    default: 'latest'
  package-path:
    description: 'The folder where the swift package is checked out'
    required: true
    default: '.'
  swift-build-flags:
    description: 'Additional flags to pass to the swift build command'
    required: true
    default: ''
  swift-test-flags:
    description: 'Additional flags to pass to the swift test command'
    required: true
    default: ''
  android-emulator-test-folder:
    description: 'Emulator folder where tests are copied and run'
    required: true
    default: '/data/local/tmp/android-xctest'
  test-env:
    description: 'Test environment variables key=value'
    required: true
    default: ''
  android-emulator-options:
    description: 'Options to pass to the Android emulator'
    required: true
    default: '-no-window -gpu swiftshader_indirect -noaudio -no-boot-anim'
  android-emulator-boot-timeout:
    description: 'Emulator boot timeout in seconds'
    required: true
    default: 600
  build-package:
    description: 'Whether to build the package or just set up the SDK'
    required: true
    default: 'true'
  build-tests:
    description: 'Whether to build the tests or just the sources'
    required: true
    default: 'true'
  run-tests:
    description: 'Whether to run the tests or just the build'
    required: true
    default: 'true'
  copy-files:
    description: 'Additional files to copy to emulator for testing'
    required: true
    default: ''
  android-api-level:
    description: 'The API level of the Android emulator to run against'
    required: true
    default: 29

runs:
  using: "composite"
  steps:
    - name: Setup swift-android-action
      id: setup
      shell: bash
      run: |
        if [ ${RUNNER_OS} == 'Linux' ]; then
          # fetch OS variables like ID ("ubuntu") and VERSION_ID ("24.04")
          . /etc/os-release
          echo "osidpair=${ID}${VERSION_ID}" >> $GITHUB_OUTPUT
          echo "osid=${ID}$(echo ${VERSION_ID} | tr -d '.')" >> $GITHUB_OUTPUT
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          echo "osidpair=macos" >> $GITHUB_OUTPUT
          echo "osid=macos" >> $GITHUB_OUTPUT
        else
          echo "::error::Unsupported platform: ${RUNNER_OS}"
          exit 1
        fi

        # RUNNER_ARCH	The architecture of the runner executing the job. Possible values are X86, X64, ARM, or ARM64.
        if [ ${RUNNER_ARCH} == 'X64' ]; then
          echo "android-sdk-arch=x86_64" >> $GITHUB_OUTPUT
          echo "android-emulator-arch=x86_64" >> $GITHUB_OUTPUT
        elif [ ${RUNNER_ARCH} == 'ARM64' ]; then
          echo "android-sdk-arch=aarch64" >> $GITHUB_OUTPUT
          echo "android-emulator-arch=arm64-v8a" >> $GITHUB_OUTPUT
        else
          echo "::error::Unsupported architecture: ${RUNNER_ARCH}"
          exit 1
        fi

        # translate swift-version "latest" into our known latest version
        if [ "${{ inputs.swift-version }}" == 'latest' ]; then
          echo "swift-version=6.0.2" >> $GITHUB_OUTPUT
        else
          echo "swift-version=${{ inputs.swift-version }}" >> $GITHUB_OUTPUT
        fi

    - name: Cache Swift ${{ steps.setup.outputs.swift-version }} Host Toolchain
      uses: actions/cache@v4
      id: cache-swift
      with:
        path: ~/swift-download
        key: "swift-${{ steps.setup.outputs.swift-version }}-${{ steps.setup.outputs.osid }}"

    - name: Download Swift Host Toolchain
      if: steps.cache-swift.outputs.cache-hit != 'true'
      shell: bash
      run: |
        SWIFT_ID="swift-${{ steps.setup.outputs.swift-version }}-RELEASE"
        mkdir -p ~/swift-download
        cd ~/swift-download
        if [ ${RUNNER_OS} == 'Linux' ]; then
          curl -fsSL https://download.swift.org/swift-${{ steps.setup.outputs.swift-version }}-release/${{ steps.setup.outputs.osid }}/${SWIFT_ID}/${SWIFT_ID}-${{ steps.setup.outputs.osidpair }}.tar.gz --output swift.tar.gz
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          curl -fsSL https://download.swift.org/swift-${{ steps.setup.outputs.swift-version }}-release/xcode/${SWIFT_ID}/${SWIFT_ID}-osx.pkg --output swift.pkg
        else
          echo "::error::Unsupported platform: ${RUNNER_OS}"
          exit 1
        fi

    - name: Install Swift Host Toolchain
      shell: bash
      run: |
        cd ~/swift-download
        SWIFT_ID="swift-${{ steps.setup.outputs.swift-version }}-RELEASE"
        if [ ${RUNNER_OS} == 'Linux' ]; then
          mkdir -p ${HOME}/swift/toolchains/$SWIFT_ID
          tar -xzf swift.tar.gz -C ${HOME}/swift/toolchains/$SWIFT_ID --strip 1
          SWIFT_INSTALLATION=$HOME/swift/toolchains/$SWIFT_ID/usr
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          /usr/sbin/installer -pkg swift.pkg -target CurrentUserHomeDirectory
          SWIFT_INSTALLATION=${HOME}/Library/Developer/Toolchains/${SWIFT_ID}.xctoolchain/usr
          echo "TOOLCHAINS=$(plutil -extract CFBundleIdentifier raw ${SWIFT_INSTALLATION}/Info.plist)" >> $GITHUB_ENV
        else
          echo "::error::Unsupported platform: ${RUNNER_OS}"
          exit 1
        fi
        echo "SWIFT_INSTALLATION=${SWIFT_INSTALLATION}" >> $GITHUB_ENV
        # needed to override locally-installed `swift` command
        #echo "${SWIFT_INSTALLATION}/bin" >> $GITHUB_PATH

    - name: Install Swift Android SDK
      id: install
      shell: bash
      run: |
        set +x
        SWIFT_SDK_ANROID_API="24"
        echo "SWIFT_SDK_ANROID_API=${SWIFT_SDK_ANROID_API}" >> $GITHUB_ENV

        SWIFT_SDK_ID="swift-${{ steps.setup.outputs.swift-version }}-RELEASE-android-${SWIFT_SDK_ANROID_API}-0.1"
        echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV

        # variant that identifies the SDK
        SWIFT_SDK_ID_SHORT="swift-${{ steps.setup.outputs.swift-version }}-release-android-${SWIFT_SDK_ANROID_API}-sdk"
        echo "SWIFT_SDK_ID_SHORT=${SWIFT_SDK_ID_SHORT}" >> $GITHUB_ENV

        SWIFT_SDK_TARGET="${{ steps.setup.outputs.android-sdk-arch }}-unknown-linux-android${SWIFT_SDK_ANROID_API}"
        echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV

        mkdir -p ${RUNNER_TEMP}/swift-android-toolchain
        cd ${RUNNER_TEMP}/swift-android-toolchain
        curl -fsSL https://github.com/skiptools/swift-android-toolchain/releases/download/${{ steps.setup.outputs.swift-version }}/${SWIFT_SDK_ID}.artifactbundle.tar.gz --output ${SWIFT_SDK_ID}.artifactbundle.tar.gz

        # first check if it already installed (we may be running this workflow multiple times for an action, in which case it will already be present)
        ${SWIFT_INSTALLATION}/bin/swift sdk configure --show-configuration ${SWIFT_SDK_ID} ${SWIFT_SDK_TARGET} &> /dev/null || ${SWIFT_INSTALLATION}/bin/swift sdk install ${SWIFT_SDK_ID}.artifactbundle.tar.gz

        ${SWIFT_INSTALLATION}/bin/swift sdk configure --show-configuration ${SWIFT_SDK_ID} ${SWIFT_SDK_TARGET}

        if [ ${RUNNER_OS} == 'Linux' ]; then
          SWIFT_SDK_ROOT="${HOME}/.config/swiftpm/swift-sdks"
        elif [ ${RUNNER_OS} == 'macOS' ]; then
          SWIFT_SDK_ROOT="${HOME}/.swiftpm/swift-sdks"
        else
          echo "::error::Unsupported platform for SDK: ${RUNNER_OS}"
          exit 1
        fi

        SWIFT_SDK_HOME="${SWIFT_SDK_ROOT}/${SWIFT_SDK_ID}.artifactbundle"

        # extract the artifact ID from the info.plist in the SDK root
        SWIFT_SDK_ARTIFACT_ID=$(cat ${SWIFT_SDK_HOME}/info.json | jq -r '.artifacts[] | .variants[0].path')
        SWIFT_SDK_HOME="${SWIFT_SDK_HOME}/${SWIFT_SDK_ARTIFACT_ID}"

        # extract the sdkRootPath from the swift-sdk.json
        SWIFT_SDK_ROOT_PATH=$(cat ${SWIFT_SDK_HOME}/swift-sdk.json | jq -r '.targetTriples[] | .sdkRootPath' | head -n 1)
        SWIFT_SDK_HOME="${SWIFT_SDK_HOME}/${SWIFT_SDK_ROOT_PATH}"

        echo "SWIFT_SDK_HOME=${SWIFT_SDK_HOME}" >> $GITHUB_ENV

        echo "swiftcmd=${SWIFT_INSTALLATION}/bin/swift build --swift-sdk ${SWIFT_SDK_TARGET} -Xswiftc -DSKIP_BRIDGE ${{ inputs.swift-build-flags }}" >> $GITHUB_OUTPUT
        echo "swift-sdk=${SWIFT_SDK_TARGET}" >> $GITHUB_OUTPUT

    - name: Check Swift Version
      shell: bash
      run: |
        echo "Swift Command: ${{ steps.install.outputs.swiftcmd }}"
        ${{ steps.install.outputs.swiftcmd }} --version

    - name: Build Swift Package with Android SDK
      if: ${{ inputs.build-package == 'true' }}
      shell: bash
      working-directory: ${{ inputs.package-path }}
      run: |
        if [ "${{ inputs.build-tests }}" == 'true' ]; then
          BUILD_TESTS="--build-tests"
        fi
        SKIP_BRIDGE=1 ${{ steps.install.outputs.swiftcmd }} ${BUILD_TESTS}

    - name: Prepare Android Emulator Test Script
      if: ${{ inputs.run-tests == 'true' && inputs.build-tests == 'true' && inputs.build-package == 'true' }}
      shell: bash
      working-directory: ${{ inputs.package-path }}
      run: |
        if [ ${RUNNER_ARCH} == 'ARM64' ] && [ ${RUNNER_OS} == 'macOS' ]; then
          echo "::error::Cannot run tests on ARM64 macOS due to HVF error: HV_UNSUPPORTED. See https://github.com/ReactiveCircus/android-emulator-runner/issues/350#issuecomment-2030065889"
          exit 1
        fi

        #inputs.android-emulator-test-folder = /data/local/tmp/android-xctest
        REMOTE_FOLDER=$(dirname "${{ inputs.android-emulator-test-folder }}")
        TEST_BASE_FOLDER=$(basename "${{ inputs.android-emulator-test-folder }}")
        BUILD_DIR=".build"
        PACK_DIR="${BUILD_DIR}/${TEST_BASE_FOLDER}"

        mkdir -p ${PACK_DIR}

        # copy the built test binary
        cp -va ${BUILD_DIR}/${SWIFT_SDK_TARGET}/debug/*.xctest ${PACK_DIR}

        # copy any optional resource bundles
        cp -vaf ${BUILD_DIR}/${SWIFT_SDK_TARGET}/debug/*.resources ${PACK_DIR} || true
        # 6.0.2 keeps libraries in per-API folders
        cp -vaf ${SWIFT_SDK_HOME}/usr/lib/${{ steps.setup.outputs.android-sdk-arch }}-linux-android/${SWIFT_SDK_ANROID_API}/lib*.so ${PACK_DIR} || true

        # 6.0.3 keeps libraries in the parent folder
        cp -vaf ${SWIFT_SDK_HOME}/usr/lib/${{ steps.setup.outputs.android-sdk-arch }}-linux-android/lib*.so ${PACK_DIR} || true

        # clear out libraries that are already provided by Android
        rm -v ${PACK_DIR}/lib{c,dl,log,m,z}.so || true

        if [ "${{ inputs.copy-files }}" != '' ]; then
          cp -vaf ${{ inputs.copy-files }} ${PACK_DIR}
        fi

        # create the script that will be run once the emulator is launched
        SCRIPT_FILE="run-android-tests.sh"

        cd ${BUILD_DIR}
        echo "adb push ${TEST_BASE_FOLDER} ${REMOTE_FOLDER}" > ${SCRIPT_FILE}
        for XCTEST in ${TEST_BASE_FOLDER}/*.xctest; do
          XCTEST_BASE=$(basename "${XCTEST}")
          echo "adb shell 'cd ${REMOTE_FOLDER}/${TEST_BASE_FOLDER} && ${{ inputs.test-env }} ./${XCTEST_BASE} ${{ inputs.swift-test-flags }}'" >> ${SCRIPT_FILE}
        done

        cat ${SCRIPT_FILE}

        chmod +x ${SCRIPT_FILE}

    - name: Setup Android Emulator Cache
      if: ${{ inputs.run-tests == 'true' && inputs.build-tests == 'true' && inputs.build-package == 'true' }}
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.android-api-level }}-${{ steps.setup.outputs.android-emulator-arch }}

    - name: Create Android Emulator Cache
      if: ${{ inputs.run-tests == 'true' && inputs.build-tests == 'true' && inputs.build-package == 'true' && steps.avd-cache.outputs.cache-hit != 'true' }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        force-avd-creation: false
        api-level: ${{ inputs.android-api-level }}
        emulator-boot-timeout: ${{ inputs.android-emulator-boot-timeout }}
        emulator-options: ${{ inputs.android-emulator-options }}
        arch: ${{ steps.setup.outputs.android-emulator-arch }}
        disable-animations: false
        working-directory: ${{ inputs.package-path }}/.build
        script: echo "Generated Android Emulator snapshot for caching."

    - name: Run Tests on Android emulator
      if: ${{ inputs.run-tests == 'true' && inputs.build-tests == 'true' && inputs.build-package == 'true' }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        force-avd-creation: false
        api-level: ${{ inputs.android-api-level }}
        emulator-boot-timeout: ${{ inputs.android-emulator-boot-timeout }}
        emulator-options: -no-snapshot-save ${{ inputs.android-emulator-options }}
        arch: ${{ steps.setup.outputs.android-emulator-arch }}
        disable-animations: true
        working-directory: ${{ inputs.package-path }}/.build
        script: ./run-android-tests.sh

